common: &common
  adapter: postgresql
  username: personal-website
  password: # from psql setup, see Postgresql
  host: localhost

development:
  <<: *common
  database: personal-webpage_development

test:
  <<: *common
  database: personal-webpage_test

#production:
#  <<: *common
#  database: personal-webpage_production
